### ISSUE TITLE
Create Releases and add build artifact

### ISSUE THREAD

**Issue by scott-au** [Zeckie/ProxyAuth#19]
it would be handy to have a pre-built jar ready to go.

**Comment by Zeckie** [comment]
Isn't that already addressed by https://github.com/Zeckie/ProxyAuth/pull/15 ?

**Comment by scott-au** [comment]
yes looks like #15 will address - didn't see an issue for it so id though id raise

**Comment by KotlinIsland** [comment]
So just need @Zeckie to approve the draft release,

**Comment by Zeckie** [comment]
There are a few issues / PRs left in [the milestone](https://github.com/Zeckie/ProxyAuth/milestone/1), with #6 being quite critical. Once those are done, it should be ready to run from a jar file.
